export const BOOK_TABLE_START = 'BOOK_TABLE_START';
export const BOOK_TABLE_SUCCESS = 'BOOK_TABLE_SUCCESS';
export const BOOK_TABLE_FAIL = 'BOOK_TABLE_FAIL';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';